[general]
import = [
    "~/.config/alacritty/themes/themes/ashes_dark.toml"
]
[cursor.style]
blinking = "Off"

# [env]
# TERM = "xterm-256color"

# [terminal]
# osc52="CopyPaste"

[font]
size = 17.0

[font.normal]
family = "JetBrainsMono NFP"
# style = "Bold"

[font.offset]
x = 0
y = 2

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
opacity = 1
startup_mode = "Windowed"
# option_as_alt = "OnlyLeft" 

# [window.dimensions]
# columns = 150
# lines = 42
#
# [window.position]
# x = 50
# y = 100

[window.padding]
x = 0
y = 0

